### ISSUE TITLE
Metanorma compile error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-samples-iho#59]
I'm trying to update a `gh-pages` branch here for PDF processing in `mn-native-pdf` repo (there is an issue with obsolete xml file there https://github.com/metanorma/mn-native-pdf/issues/253) and get these errors here (see last commit https://github.com/metanorma/mn-samples-iho/commit/307ceb18629c1b218adbd07a5c2cbd2cf685d3fd):

- docker (step `Build document in the Metanorma container`):
```
Errno::ENOENT: No such file or directory @ rb_sysopen - lib/isodoc/iho/i18n-en.yaml
  /usr/local/lib/ruby/2.6.0/psych.rb:577:in `initialize'
  /usr/local/lib/ruby/2.6.0/psych.rb:577:in `open'
  /usr/local/lib/ruby/2.6.0/psych.rb:577:in `load_file'
  /usr/local/bundle/gems/isodoc-1.2.4/lib/isodoc/i18n.rb:7:in `load_yaml'
  /usr/local/bundle/gems/isodoc-1.2.4/lib/isodoc/i18n.rb:38:in `initialize'
```

- ubuntu (step `Use Metanorma`), similar error
```
bundler: failed to load command: metanorma (/usr/local/bin/metanorma)
Errno::ENOENT: No such file or directory @ rb_sysopen - lib/isodoc/iho/i18n-en.yaml
  /usr/lib/ruby/2.5.0/psych.rb:497:in `initialize'
  /usr/lib/ruby/2.5.0/psych.rb:497:in `open'
  /usr/lib/ruby/2.5.0/psych.rb:497:in `load_file'
  /var/lib/gems/2.5.0/gems/isodoc-1.2.4/lib/isodoc/i18n.rb:7:in `load_yaml'
  /var/lib/gems/2.5.0/gems/isodoc-1.2.4/lib/isodoc/i18n.rb:38:in `initialize'
```

- macos (step ` Use Metanorma`)

```
==> Downloading https://homebrew.bintray.com/bottles/yq-3.3.4.catalina.bottle.tar.gz
==> Pouring yq-3.3.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/yq/3.3.4: 5 files, 5.7MB
Error: Calling Non-checksummed download of metanorma formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
```

- windows (Install Metanorma & yq)
```
Failures
 - metanorma (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\metanorma\tools\chocolateyinstall.ps1'.
```

**Comment by Intelligent2013** [comment]
There isn't issue.
